media:
  input: images
  output: /
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view:
      fields: [ title, published, date ]
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: description
        label: Description
        type: string
      - name: summary
        label: Summary
        type: string
      - name: tags
        label: Tags
        type: string
      - name: minute
        type: Minute
        type: number