media:
  input: images
  output: /
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view:
      fields: [ title, summary, date ]
    fields:
      - name: date
        label: Date
        type: date
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true
      - name: description
        label: Description
        type: string
      - name: summary
        label: Summary
        type: string
      - name: tags
        label: Tags
        type: string
      - name: minute
        label: Minute
        type: number
      - name: image
        label: Image
        type: image
      - name: layout
        type: string
        label: Layout
        default: post
        required: true
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: title
        label: Website title
        type: string
      - name: aboutme
        label: About me
        type: string
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: logo
        label: Logo image        
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)