title: hen.ee
email: contact@hen.ee
aboutme: >-
  Student, frontend web developer and Linux sysadmin based in Tallinn, Estonia.
description: Student, frontend web developer and Linux sysadmin based in Estonia. 
tagline: Frontend web developer and Linux sysadmin.
baseurl: "" 
url: "https://hen.ee" 
permalink: "https://hen.ee/"
permalink: /:title/
lang: en-US
timezone: Europe/London

aboutme-text: >-
  <p>Mainly my expertise is in frontend web development. I sometimes tinker with Linux, open-source software and servers. I am keen on learning new technology or on how old technology can still suit us better even today.</p>

  <p>Sometimes I write <a class="down" href="#recents">in my blog</a> about whatever pseudo-intellectual nonsense I have on my mind — mostly nerdy technological ramblings but could extend to a discussion into random personal topics. I'm also quite interested in internet privacy, self-hosting and web decentralisation.</p>

  <p>Find me on <a class="outside" rel="me" href="https://mastodon.social/@henriaunin">Mastodon</a>, <a class="outside" rel="me" href="https://github.com/tenseoverflow">Github</a> or send me an e-mail to <a href="mailto:contact@hen.ee" rel="me">contact@hen.ee</a> (<a href="https://hen.ee/hen.asc">GPG</a>).</p>

# estonian
aboutme-est: >-
  Veebidisainer ja arendaja Tallinnast.
aboutme-text-est: >-
  <p>Tegelen peamiselt veebidisaini ja -arendusega. Vahest ka <i>open-source</i> tarkvaraga ning Linuxiga.</p>

  <p>Vahest kirjutan <a href="#recents" class="down">blogisse</a> midagi huvitavat. Peamiselt inglise keeles, aga kui jõuan, siis ka eesti keeles.</p>

  <p>Jälgi mind <a class="outside" href="https://mastodon.social/@henriaunin">Mastodonis</a>, <a class="outside" href="https://github.com/tenseoverflow">Githubis</a> või saada e-mail <a href="mailto:contact@hen.ee">contact@hen.ee</a> (<a href="https://hen.ee/hen.asc">GPG</a>).</p>

author: Henri Aunin
social:
  links:
    - https://github.com/tenseoverflow
    - https://twitter.com/henriaunin
    - https://mastodon.social/@henriaunin
twitter:
  username: henriaunin
  card: summary

logo: /images/day-400-nohill.png

# Build settings
#theme: default
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - FUNDING.md
