title: hen.ee
email: contact@hen.ee
aboutme: >- # this means to ignore newlines until "baseurl:"
  <p>I am a developer, an online privacy supporter and a digital independent<sup><a href="https://hen.ee/digitalindependent">*</a></sup>.</p>

  <p>I provide some self-hosted instances.</p>

  <p>I also think the modern web is privacy-invasive, over-engineered, slow and vulnerable. I elaborate on these ideas in my blog with other topics about technology, privacy, culture, lifestyle, current news etc; maybe even finance.</p>
description: I am a developer, an online privacy supporter and a digital independent. In my blog, I write about technology, privacy and other things on my mind.
tagline: A blog dedicated to my thoughts.
baseurl: "" 
url: "https://hen.ee" 
permalink: "https://hen.ee/"
permalink: pretty
lang: en-US
timezone: Europe/London
repo: https://github.com/tenseoverflow/hen.ee
#data-theme: light

author: Henri
social:
  links:
    - https://github.com/tenseoverflow
    - https://join.status.im/u/0x0423fc98719e5b46461de2cdb3f83f1d48e336ce46b5ae15f6bfd654b6b1fdd73380e23554449b55f0e1f5d4a6a0f6fa6edd2840152b91b0ae09f6a4dac690c28d
    - 

about:
- title: status.im
  url: https://hen.ee/statusim
  name: '0x0423fc98719e5b46461de2cdb3f83f1d48e336ce46b5ae15f6bfd654b6b1fdd73380e23554449b55f0e1f5d4a6a0f6fa6edd2840152b91b0ae09f6a4dac690c28d'
- title: Github
  url: https://github.com/tenseoverflow
  name: tenseoverflow
- title: Discord
  name: Straton of Stageira#6830

# Build settings
#theme: default
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - FUNDING.md
